#if !canImport(ObjectiveC)
import XCTest

extension BreadthFirstSequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BreadthFirstSequenceTests = [
        ("test", test),
    ]
}

extension DepthFirstSequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DepthFirstSequenceTests = [
        ("test", test),
    ]
}

extension InterspersedSequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InterspersedSequenceTests = [
        ("testArrayEmpty", testArrayEmpty),
        ("testArrayJoin", testArrayJoin),
        ("testStringEmpty", testStringEmpty),
        ("testStringJoin", testStringJoin),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BreadthFirstSequenceTests.__allTests__BreadthFirstSequenceTests),
        testCase(DepthFirstSequenceTests.__allTests__DepthFirstSequenceTests),
        testCase(InterspersedSequenceTests.__allTests__InterspersedSequenceTests),
    ]
}
#endif
