#if !canImport(ObjectiveC)
import XCTest

extension BreadthFirstSequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BreadthFirstSequenceTests = [
        ("test", test),
    ]
}

extension DepthFirstSequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DepthFirstSequenceTests = [
        ("test", test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BreadthFirstSequenceTests.__allTests__BreadthFirstSequenceTests),
        testCase(DepthFirstSequenceTests.__allTests__DepthFirstSequenceTests),
    ]
}
#endif
